spring:
  application:
    name: frankit
  datasource:
    url: jdbc:mariadb://localhost:3306/frankitshop
    username: frankitadmin
    password: frankitpw
    driver-class-name: org.mariadb.jdbc.Driver

