spring:
  application:
    name: frankit
  datasource:
    url: jdbc:mariadb://localhost:3306/frankitshop
    username: frankitadmin
    password: frankitpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create #개발 완료후 update로 수정예정
